apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
      - name: student-backend
        image: johnson1174/student-backend:latest
        ports:
        - containerPort: 80  # ← Change from 5000 to 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: student-backend-service
spec:
  type: LoadBalancer
  selector:
    app: student-backend
  ports:
  - port: 80
    targetPort: 80  # ← Change from 5000 to 80